<<<<<<< HEAD
spring.application.name=SpaceBook
spring.datasource.url=jdbc:mysql://localhost:3306/spacebook
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
=======
spring.application.name=demo
>>>>>>> 5403a17debb82bb20f84bb95ffe71863ebd9c109
